"""
Custody Agreement PDF Generator — Carbon Credit Custody Agreement.

Generates a branded PDF with:
  - NIHA data pre-filled (italic blue font)
  - Client data pre-filled where available, blank lines where not
  - Full 18-article Custody Agreement + 3 Schedules
  - NIHA representative signature pre-applied
  - Counterparts clause for wet-ink execution
"""

from datetime import date, datetime
from typing import Optional

from reportlab.platypus import Spacer, PageBreak, Paragraph, Table, TableStyle
from reportlab.lib.units import mm

from .styles import (
    build_niha_pdf,
    gold_separator,
    thin_separator,
    filled,
    niha_party_block,
    client_party_block,
    signature_block,
    key_terms_table,
    NihaFonts,
    NihaColors,
)
from .msa_generator import _data_table


def generate_custody_pdf(
    client_entity_name: Optional[str] = None,
    client_entity_type: Optional[str] = None,
    client_jurisdiction: Optional[str] = None,
    client_representative: Optional[str] = None,
    client_email: Optional[str] = None,
    effective_date: Optional[date] = None,
    doc_ref: Optional[str] = None,
    output_path: Optional[str] = None,
) -> bytes:
    """Generate the NIHA Carbon Credit Custody Agreement as a branded PDF."""
    eff_date = effective_date or date.today()
    ref = doc_ref or f"NIHA-CUST-{eff_date.strftime('%Y')}-{eff_date.strftime('%m%d')}"

    def content(styles):
        el = []

        # ── TITLE PAGE ──
        el.append(Spacer(1, 15 * mm))
        el.append(Paragraph("CARBON CREDIT", styles['DocTitle']))
        el.append(Paragraph("CUSTODY AGREEMENT", styles['DocTitle']))
        el.append(Spacer(1, 2 * mm))
        el.append(Paragraph("(Safekeeping, Segregation &amp; Delivery)", styles['DocSubtitle']))
        el.append(gold_separator())

        date_str = eff_date.strftime("%d %B %Y")
        el.append(Paragraph(f"Effective Date: {filled(date_str)}", styles['Body']))
        el.append(Paragraph(f"Reference: {filled(ref)}", styles['Body']))
        el.append(Paragraph(
            f"Governed by the Laws of {filled('Hong Kong Special Administrative Region')}",
            styles['Body']))
        el.append(Spacer(1, 5 * mm))

        # ── PARTIES ──
        el.append(Paragraph("between", styles['Body']))
        el.append(Spacer(1, 3 * mm))
        el.extend(niha_party_block(styles, label="Custodian"))
        el.append(Spacer(1, 3 * mm))
        el.append(Paragraph("and", styles['Body']))
        el.append(Spacer(1, 3 * mm))
        el.extend(client_party_block(
            styles, label="Client",
            entity_name=client_entity_name,
            entity_type=client_entity_type,
            jurisdiction=client_jurisdiction,
            representative=client_representative,
            email=client_email,
        ))
        el.append(Spacer(1, 5 * mm))

        # Helper for clause blocks
        def clause(num, text):
            el.append(Paragraph(f'<b>{num}</b> {text}', styles['SubClause']))

        def items(lst):
            for item in lst:
                el.append(Paragraph(item, styles['SubClauseItem']))

        def article(title):
            el.append(Paragraph(title, styles['ClauseNumber']))
            el.append(thin_separator())

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 1 — DEFINITIONS AND INTERPRETATION
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 1 — DEFINITIONS AND INTERPRETATION")
        clause('1.1', 'In this Agreement, unless the context otherwise requires, the following terms shall have the meanings set out below:')

        defs = [
            ('"Applicable Law"', 'means all laws, regulations, rules, orders, directives, circulars, and guidelines applicable in Hong Kong SAR, the European Union, the PRC, and any other relevant jurisdiction, as amended from time to time.'),
            ('"Business Day"', 'means a day on which banks are open for general business in Hong Kong SAR, excluding Saturdays, Sundays, and gazetted public holidays.'),
            ('"Carbon Credits"', 'means any and all carbon emission allowances, certificates, or credits, including: (i) European Union Allowances ("EUA"); (ii) China Emission Allowances ("CEA"); (iii) China Certified Emission Reductions ("CCER"); and (iv) voluntary carbon credits ("VCC").'),
            ('"Client Ledger"', 'means the internal record maintained by the Custodian through the Platform, recording the Client\'s beneficial interest in Carbon Credits, including type, volume, acquisition date, and cost basis.'),
            ('"Confirmation"', 'means the electronic document generated by the Platform evidencing the terms of a Transaction, accessible to the Client through the Platform and delivered by email.'),
            ('"Custodian Account"', 'means the account(s) maintained by the Custodian at the relevant Registry for holding Carbon Credits.'),
            ('"Instruction"', 'means a written instruction from the Client to the Custodian, delivered through the Platform or by authenticated electronic means, in the form and manner prescribed by the Custodian from time to time.'),
            ('"MSA"', 'means the Master Service Agreement entered into between the parties on or about the date of this Agreement.'),
            ('"NDA"', 'means the Non-Disclosure and Non-Circumvention Agreement entered into between the parties on or about the date of this Agreement.'),
            ('"Platform"', f'means the NIHA Carbon Platform accessible at {filled("https://nihacarbon.com")} or such successor URL as the Custodian may notify to the Client.'),
            ('"Registry"', 'means any registry or platform used for the issuance, holding, transfer, retirement, or cancellation of Carbon Credits, including those listed in Schedule B.'),
            ('"Segregated Account"', 'means the segregated client money account described in Article 6.'),
            ('"Transaction"', 'means any acquisition, sale, conversion (swap), delivery, retirement, or transfer of Carbon Credits pursuant to this Agreement or the MSA.'),
        ]
        for term, defn in defs:
            el.append(Paragraph(f'<b>{term}</b> {defn}', styles['SubClauseItem']))

        clause('1.2', 'References to "parties" means the Custodian and the Client, and "party" means either of them.')
        clause('1.3', 'Headings are for convenience only and shall not affect interpretation.')
        clause('1.4', 'References to legislation include amendments, re-enactments, and subsidiary legislation.')
        clause('1.5', 'This Agreement shall be read in conjunction with the MSA and the NDA. In the event of conflict: (i) regarding confidentiality and non-circumvention, the NDA shall prevail; (ii) regarding service scope and execution, the MSA shall prevail; (iii) regarding custody and safekeeping, this Agreement shall prevail.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 2 — APPOINTMENT AND ROLE
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 2 — APPOINTMENT AND ROLE OF THE CUSTODIAN")
        clause('2.1', 'The Client hereby appoints the Custodian to acquire, hold, manage, and deal with Carbon Credits in accordance with the terms of this Agreement. The Custodian accepts such appointment.')
        clause('2.2', 'The Client acknowledges and agrees that the Custodian acts as a facilitator of cross-border carbon credit transactions. Due to the structural separation between EU and PRC carbon markets, the Custodian necessarily acquires Carbon Credits in its own name as principal to effect cross-border value exchanges for the Client. The Client acknowledges that this principal structure is essential to the Service Provider\'s business model.')

        clause('2.3', 'For the avoidance of doubt, the Custodian is NOT acting as:')
        items([
            '(a) a trustee or fiduciary, except to the extent expressly stated in this Agreement regarding the segregation of Carbon Credits and Client funds;',
            '(b) an investment adviser or financial adviser;',
            '(c) an exchange or marketplace operator.',
        ])

        clause('2.4', 'The Custodian\'s obligation under this Agreement is to deliver Carbon Credits equivalent in type and volume to those recorded in the Client Ledger, upon the Client\'s valid Instruction. The Custodian does not guarantee the future value or liquidity of Carbon Credits.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 3 — CUSTODY ARRANGEMENTS
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 3 — CUSTODY ARRANGEMENTS")
        clause('3.1', '<b>Segregation.</b> The Custodian shall maintain the Client Ledger as a separate record, distinguishing the Client\'s beneficial holdings from: (i) the Custodian\'s proprietary Carbon Credits; and (ii) Carbon Credits held on behalf of other clients.')
        clause('3.2', '<b>Omnibus Accounts.</b> The Client acknowledges that Carbon Credits may be held in omnibus accounts at the relevant Registry. The Custodian shall at all times maintain accurate sub-account records through the Client Ledger to evidence the Client\'s beneficial interest.')
        clause('3.3', '<b>No Encumbrance.</b> The Custodian shall not pledge, lend, hypothecate, or otherwise encumber any Carbon Credits in which the Client holds a beneficial interest, without the prior written consent of the Client, except as may be required by Applicable Law or court order.')
        clause('3.4', '<b>Security.</b> The Custodian shall implement and maintain reasonable security measures to protect Registry account credentials, including but not limited to multi-factor authentication, IP whitelisting, and encryption of sensitive data.')
        clause('3.5', '<b>Sub-Custody.</b> The Custodian may appoint sub-custodians for the purpose of holding Carbon Credits at specific Registries, provided that: (i) the Custodian gives the Client prior written notice; (ii) the sub-custodian is a regulated entity with appropriate custody experience; and (iii) the Custodian remains liable to the Client for the performance of the sub-custodian.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 4 — CLIENT INSTRUCTIONS AND TRANSACTIONS
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 4 — CLIENT INSTRUCTIONS AND TRANSACTIONS")
        clause('4.1', 'The Client may issue Instructions to the Custodian through the Platform for:')
        items([
            '(a) acquisition of Carbon Credits at prices agreed between the parties or at prevailing market prices;',
            '(b) conversion (swap) of Carbon Credits from one type to another through the Custodian\'s cross-border principal counterparty mechanism;',
            '(c) delivery of Carbon Credits to a third-party Registry account designated by the Client;',
            '(d) retirement of Carbon Credits in the Client\'s name for compliance or voluntary purposes;',
            '(e) sale of Carbon Credits at prices agreed between the parties.',
        ])
        clause('4.2', 'Each Transaction shall be documented by a Confirmation generated by the Platform, specifying the type, volume, price, settlement date, and any special conditions.')
        clause('4.3', 'The Custodian shall use commercially reasonable efforts to execute Instructions within the settlement windows specified in Article 5.')
        clause('4.4', 'The Custodian may decline an Instruction if: (i) it would cause the Custodian to breach Applicable Law; (ii) the Client has insufficient funds on deposit; (iii) market conditions render execution impracticable; or (iv) the requested Carbon Credits are not available in the relevant market.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 5 — SETTLEMENT TIMELINES
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 5 — SETTLEMENT TIMELINES")
        clause('5.1', 'Standard settlement windows are as follows (all timelines expressed in Business Days from trade date "T"):')

        settle = _data_table(styles,
            headers=["Transaction Type", "Settlement Window"],
            rows=[
                ["CEA Cash Purchase", filled("T+3 (standard); T+5 (complex)")],
                ["Swap — CEA leg", filled("T+2")],
                ["Swap — EUA leg", filled("T+2")],
                ["EUA Spot Purchase", filled("T+2")],
                ["Retirement", filled("T+5")],
                ["Delivery to Third-Party Registry", filled("T+3")],
            ],
            col_widths=[85 * mm, 85 * mm],
        )
        el.append(settle)
        el.append(Spacer(1, 3 * mm))

        clause('5.2', f'If the Custodian is unable to settle by the settlement date due to causes beyond its reasonable control (including Registry delays, regulatory actions, or counterparty defaults), the Custodian shall notify the Client and propose an alternative settlement date, typically within {filled("five (5) additional Business Days")}.')
        clause('5.3', 'If settlement cannot be effected within the extended period, the Client may elect to: (i) continue to wait; (ii) cancel the Transaction and receive a full refund of funds paid; or (iii) accept alternative Carbon Credits of equivalent value.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 6 — CLIENT FUNDS
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 6 — CLIENT FUNDS")
        clause('6.1', 'The Client shall deposit funds with the Custodian in advance of Transactions, by wire transfer to the Designated Bank Account set out in Schedule C.')
        clause('6.2', f'Client funds shall be held in a segregated bank account (the "Segregated Account") at a {filled("licensed Hong Kong bank")}, separate from the Custodian\'s operational accounts.')
        clause('6.3', 'The Custodian shall not use Client funds for any purpose other than: (i) executing Transactions on behalf of the Client; (ii) deducting accrued fees and charges; and (iii) returning funds to the Client as appropriate.')
        clause('6.4', 'Interest (if any) accrued on the Segregated Account shall be applied in accordance with the terms agreed between the Custodian and the Client at the time of account opening. The Custodian makes no representation regarding interest rates.')
        clause('6.5', f'The Client may request return of any unencumbered funds by written Instruction through the Platform. The Custodian shall effect the return within {filled("five (5) Business Days")} of receipt of such Instruction.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 7 — FEES AND CHARGES
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 7 — FEES AND CHARGES")
        clause('7.1', 'The Client shall pay the Custodian fees in accordance with the Fee Schedule set out in Schedule A.')
        clause('7.2', 'Fees are payable in the currency specified in Schedule A. The Custodian may deduct fees from the Client\'s funds held in the Segregated Account or from the Client\'s Carbon Credit holdings (as applicable), provided that written notice is given and the fee has accrued.')
        clause('7.3', 'Registry fees, transfer fees, and third-party charges shall be passed through to the Client at cost, without mark-up.')
        clause('7.4', f'The Custodian may revise the Fee Schedule by giving {filled("sixty (60) days")} written notice to the Client. Any single revision shall not increase any fee rate by more than {filled("twenty-five percent (25%)")} relative to the then-current rate.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 8 — REPORTING AND RECORDS
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 8 — REPORTING AND RECORDS")
        clause('8.1', '<b>Platform Access.</b> The Client shall have real-time access through the Platform to:')
        items([
            '(a) current Carbon Credit holdings by type and volume;',
            '(b) transaction history and Confirmations;',
            '(c) current market valuation of holdings;',
            '(d) EUR balance in the Segregated Account, including deposits, withdrawals, and fees.',
        ])
        clause('8.2', f'<b>Monthly Statements.</b> The Custodian shall make available through the Platform a monthly statement within {filled("ten (10) Business Days")} following the end of each calendar month, showing opening and closing balances of Carbon Credits and funds, all Transactions, fees deducted, and accrued interest (if any).')
        clause('8.3', '<b>Annual Reconciliation.</b> The Custodian shall conduct an annual internal reconciliation to confirm that: (i) the Client Ledger accurately reflects the Carbon Credits held in Custodian Accounts; and (ii) Client funds in the Segregated Account match recorded balances.')
        clause('8.4', f'<b>Record Retention.</b> The Custodian shall maintain all records relating to this Agreement for a minimum period of {filled("seven (7) years")} following termination, in accordance with applicable record-keeping legislation.')
        clause('8.5', '<b>Inspection Rights.</b> The Client or its authorised representative shall have the right to inspect the Custodian\'s records relating to the Client\'s holdings upon reasonable prior written notice during normal business hours.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 9 — REPRESENTATIONS AND WARRANTIES
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 9 — REPRESENTATIONS AND WARRANTIES")
        clause('9.1', 'Each party represents and warrants to the other that, as of the Effective Date and on each trade date:')
        items([
            '(a) it is duly organised and validly existing under the laws of its jurisdiction;',
            '(b) it has full corporate power and authority to enter into and perform this Agreement;',
            '(c) this Agreement constitutes a legal, valid, and binding obligation;',
            '(d) no consent, approval, or authorisation of any governmental authority is required that has not been obtained;',
            '(e) it is not insolvent, bankrupt, or subject to winding-up or analogous proceedings.',
        ])
        clause('9.2', 'The Custodian additionally represents that:')
        items([
            '(a) it has adequate operational, technical, and compliance infrastructure to perform its obligations hereunder;',
            '(b) it implements AML/KYC procedures aligned with applicable anti-money laundering and counter-terrorist financing legislation in Hong Kong;',
            '(c) it has access to the relevant Registries necessary to execute Transactions, as listed in Schedule B;',
            '(d) should any new regulatory requirement be introduced that materially affects the custody arrangements, the Custodian shall promptly notify the Client and take all reasonable steps to comply or to propose alternative arrangements.',
        ])

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 10 — RISK DISCLOSURES AND LIABILITY
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 10 — RISK DISCLOSURES AND LIABILITY")
        clause('10.1', 'The Client acknowledges and accepts the following risks:')
        risk_items = [
            ('(a)', '<b>Market Risk:</b> The value of Carbon Credits may fluctuate significantly due to changes in supply, demand, regulation, and policy. The Custodian makes no representation as to future valuations.'),
            ('(b)', '<b>Regulatory Risk:</b> Changes in applicable emissions trading systems or Hong Kong regulatory framework may affect the validity, transferability, or value of Carbon Credits.'),
            ('(c)', '<b>Registry Risk:</b> Carbon Credits exist solely as digital entries in government or approved registries. The Custodian is not liable for registry downtime, errors, or unauthorised access not caused by the Custodian\'s gross negligence.'),
            ('(d)', '<b>Cross-Border Risk:</b> Transactions involve multiple jurisdictions and currencies. Exchange rate fluctuations may affect the value of the Client\'s holdings.'),
            ('(e)', '<b>Counterparty Risk:</b> The Client\'s beneficial interest in Carbon Credits depends on the Custodian\'s continued solvency and ability to perform.'),
            ('(f)', '<b>Liquidity Risk:</b> Certain markets (particularly PRC pilot schemes) may have limited liquidity, affecting execution timing and pricing.'),
        ]
        for lbl, text in risk_items:
            el.append(Paragraph(f'{lbl} {text}', styles['SubClauseItem']))

        clause('10.2', 'The Custodian\'s aggregate liability under or in connection with this Agreement shall not exceed the value of the Carbon Credits and funds held on behalf of the Client at the time the liability arises.')
        clause('10.3', 'Neither party shall be liable for indirect, consequential, special, or punitive damages, including loss of profits, except where such damages arise from fraud, wilful misconduct, or breach of confidentiality obligations.')
        clause('10.4', 'Nothing in this Agreement shall exclude or limit either party\'s liability for fraud, wilful default, death or personal injury caused by negligence, or any liability that cannot be excluded or limited under Applicable Law.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 11 — INSOLVENCY PROTECTION
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 11 — INSOLVENCY PROTECTION")
        clause('11.1', 'The parties acknowledge that this Agreement is intended to create a custody relationship whereby the Client\'s beneficial interest in Carbon Credits is protected in the event of the Custodian\'s insolvency, to the extent permitted by Applicable Law.')
        clause('11.2', 'The Custodian shall maintain at all times sufficient Carbon Credits in its Custodian Accounts to satisfy the aggregate beneficial interests of all clients as recorded in their respective Client Ledgers.')
        clause('11.3', 'In the event of the Custodian\'s insolvency, the Client\'s beneficial interest in Carbon Credits as recorded in the Client Ledger shall have priority over unsecured creditors to the extent permitted by Applicable Law and the insolvency regime applicable to the Custodian.')
        clause('11.4', 'Client funds in the Segregated Account shall not form part of the Custodian\'s estate in insolvency and shall be returned to the Client in accordance with Applicable Law.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 12 — CONFIDENTIALITY
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 12 — CONFIDENTIALITY")
        clause('12.1', 'Each party shall keep confidential all Confidential Information (as defined in the NDA) received from the other in connection with this Agreement, including but not limited to: custody arrangements, transaction details, Client Ledger information, and pricing.')
        clause('12.2', 'The confidentiality obligations under this Article 12 are supplementary to and shall be read in conjunction with the NDA. In the event of any conflict or inconsistency, the NDA shall prevail.')
        clause('12.3', 'Exceptions to confidentiality: information that is publicly available through no fault of the receiving party, independently developed, lawfully received from a third party without restriction, or required to be disclosed by law or court order.')
        clause('12.4', f'This confidentiality obligation survives termination for a period of {filled("five (5) years")}.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 13 — AML AND COMPLIANCE
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 13 — ANTI-MONEY LAUNDERING AND COMPLIANCE")
        clause('13.1', 'The Client shall provide all information and documentation reasonably requested by the Custodian for AML/KYC purposes in a timely manner.')
        clause('13.2', f'The Custodian may suspend custody services or refuse to execute a Transaction if the Client fails to provide requested AML/KYC information within {filled("ten (10) Business Days")}.')
        clause('13.3', 'The Custodian reserves the right to file suspicious transaction reports with the appropriate authorities without notifying the Client, as required by applicable law.')
        clause('13.4', 'The Client represents that:')
        items([
            '(a) it is not a sanctioned person or entity under the sanctions programmes of the United Nations, European Union, United States, United Kingdom, or Hong Kong;',
            '(b) funds deposited with the Custodian are derived from lawful sources;',
            '(c) it will not use the custody services for money laundering, terrorist financing, sanctions evasion, or any unlawful purpose.',
        ])

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 14 — ANTI-BRIBERY
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 14 — ANTI-BRIBERY AND ANTI-CORRUPTION")
        clause('14.1', 'Each party represents that it has not, and undertakes that it shall not, in connection with this Agreement:')
        items([
            '(a) offer, promise, give, or authorise the giving of any bribe, kickback, or other corrupt payment to any person;',
            '(b) request, agree to receive, or accept any bribe, kickback, or other corrupt payment;',
            '(c) take any action that would cause either party to violate applicable anti-bribery and anti-corruption legislation.',
        ])
        clause('14.2', 'Each party shall maintain adequate procedures designed to prevent bribery and corruption by its officers, employees, agents, and any persons performing services on its behalf.')
        clause('14.3', 'A breach of this Article shall constitute a material breach entitling the non-breaching party to terminate this Agreement immediately pursuant to Article 16.3.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 15 — NON-CIRCUMVENTION
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 15 — NON-CIRCUMVENTION")
        clause('15.1', 'The non-circumvention and non-solicitation obligations set out in the NDA are hereby incorporated by reference and shall apply mutatis mutandis to the parties\' relationship under this Agreement.')
        clause('15.2', f'Without prejudice to the generality of the NDA provisions, the Client undertakes that during the term of this Agreement and for a period of {filled("two (2) years")} following its termination, it shall not directly or indirectly contact, deal with, or transact with any Protected Relationship of the Custodian for carbon credit business that would circumvent the Custodian\'s services, or use information obtained through the Platform to identify or approach counterparties.')
        clause('15.3', 'This Article 15 shall not restrict the Client from conducting business with any person or entity with whom the Client had a pre-existing relationship prior to the date of this Agreement, evidenced by written documentation.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 16 — TERM AND TERMINATION
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 16 — TERM AND TERMINATION")
        clause('16.1', f'This Agreement commences on the Effective Date and continues for an initial term of {filled("twelve (12) months")}, automatically renewing for successive twelve-month periods unless terminated in accordance with this Article.')
        clause('16.2', f'Either party may terminate by giving {filled("ninety (90) days")} written notice before the end of the then-current term.')
        clause('16.3', 'Either party may terminate immediately by written notice if:')
        items([
            f'(a) the other party commits a material breach that is not remedied within {filled("thirty (30) days")} of written notice specifying the breach;',
            '(b) the other party becomes insolvent, enters into liquidation, or is subject to analogous proceedings;',
            '(c) a change in Applicable Law makes performance of this Agreement unlawful;',
            '(d) the other party commits a breach of Article 14 (Anti-Bribery).',
        ])
        clause('16.4', 'Upon termination, the Custodian shall:')
        items([
            f'(a) transfer all Carbon Credits recorded in the Client Ledger to a Registry account designated by the Client, within {filled("twenty (20) Business Days")};',
            f'(b) return all Client funds (net of accrued fees and charges) in the Segregated Account within {filled("ten (10) Business Days")};',
            f'(c) deliver a final statement of account within {filled("twenty (20) Business Days")}.',
        ])
        clause('16.5', 'Termination shall not affect accrued rights or obligations, nor obligations that by their nature survive termination, including: confidentiality (Article 12 and NDA), non-circumvention (Article 15 and NDA), and indemnification obligations.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 17 — GOVERNING LAW
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 17 — GOVERNING LAW AND DISPUTE RESOLUTION")
        clause('17.1', f'This Agreement is governed by and shall be construed in accordance with the laws of {filled("Hong Kong Special Administrative Region")}.')
        clause('17.2', f'<b>Negotiation:</b> In the event of any dispute, the parties shall first attempt to resolve through good faith negotiations within {filled("thirty (30) days")} of written notice.')
        clause('17.3', f'<b>Mediation:</b> If not resolved, either party may refer the dispute to mediation administered by the {filled("Hong Kong Mediation Centre")}.')
        clause('17.4', f'<b>Arbitration:</b> If not resolved through mediation within {filled("sixty (60) days")}, either party may refer the dispute to final and binding arbitration under the {filled("HKIAC Administered Arbitration Rules")}.')
        clause('17.5', 'Notwithstanding the above, either party may seek injunctive or other equitable relief from the courts of Hong Kong.')

        # ════════════════════════════════════════════════════════════════
        # ARTICLE 18 — GENERAL PROVISIONS
        # ════════════════════════════════════════════════════════════════
        article("ARTICLE 18 — GENERAL PROVISIONS")
        a18 = [
            ('<b>18.1</b>', '<b>Entire Agreement:</b> This Agreement (together with the NDA, the MSA, and all Schedules) constitutes the entire agreement between the parties regarding the custody and safekeeping of Carbon Credits.'),
            ('<b>18.2</b>', '<b>Amendments:</b> No amendment shall be effective unless in writing and signed by an authorised representative of each party.'),
            ('<b>18.3</b>', '<b>Waiver:</b> No failure or delay in exercising any right shall constitute a waiver of that right.'),
            ('<b>18.4</b>', '<b>Severability:</b> If any provision is held invalid, the remaining provisions shall continue in full force and effect.'),
            ('<b>18.5</b>', f'<b>Assignment:</b> Neither party may assign without prior written consent. The Custodian may assign to a wholly-owned subsidiary upon {filled("thirty (30) days")} written notice.'),
            ('<b>18.6</b>', '<b>Third Party Rights:</b> Nothing in this Agreement confers rights on any third party.'),
            ('<b>18.7</b>', '<b>Notices:</b> All notices shall be in writing and delivered to the addresses set out in Schedule C. Notices by email shall be valid only if followed by a hard copy within five (5) Business Days.'),
            ('<b>18.8</b>', '<b>Counterparts:</b> This Agreement may be executed in counterparts, each of which shall constitute an original.'),
            ('<b>18.9</b>', '<b>Order of Precedence:</b> In the event of conflict between this Agreement and any Schedule, this Agreement shall prevail. The hierarchy between this Agreement, the MSA, and the NDA is set out in Article 1.5.'),
        ]
        for num, text in a18:
            el.append(Paragraph(f'{num} {text}', styles['SubClause']))

        # ════════════════════════════════════════════════════════════════
        # SCHEDULES
        # ════════════════════════════════════════════════════════════════
        el.append(PageBreak())
        el.append(Paragraph("SCHEDULE A — FEE SCHEDULE", styles['SectionHeading']))
        el.append(gold_separator())

        fee_table = _data_table(styles,
            headers=["Service", "Fee Rate", "Currency / Basis"],
            rows=[
                ["CEA Cash Purchase", filled("1.5%"), "of transaction value (EUR), per trade"],
                ["CEA-to-EUA Swap", filled("2.0%"), "of CEA volume (whole units, rounded up)"],
                ["EUA Spot Trade", filled("1.5%"), "of transaction value (EUR), per trade"],
                ["Carbon Credit Custody", filled("0.02% / month"), "of AUM (mark-to-market)"],
                ["Account Maintenance", filled("EUR 250 / quarter"), "per currency account"],
            ],
            col_widths=[60 * mm, 50 * mm, 60 * mm],
        )
        el.append(fee_table)
        el.append(Spacer(1, 3 * mm))
        el.append(Paragraph('<b>Notes:</b> All fees exclusive of VAT/GST. Fee cap: 25% max increase per revision (Article 7.4).', styles['Body']))

        # Schedule B
        el.append(PageBreak())
        el.append(Paragraph("SCHEDULE B — APPROVED REGISTRIES", styles['SectionHeading']))
        el.append(gold_separator())
        el.append(Paragraph(
            'This list may be updated by the Custodian from time to time with prior written notice.',
            styles['Body']))
        el.append(Spacer(1, 3 * mm))

        reg_table = _data_table(styles,
            headers=["Registry / Market", "Region", "Credit Types", "Access"],
            rows=[
                [filled("EU Transaction Log (EUTL)"), "EU", "EUA", "Via EU counterparty"],
                [filled("CEEX Shenzhen"), "PRC", "SZA, CCER", "Direct participation"],
                [filled("Shanghai Env. & Energy Exchange"), "PRC", "CCER, CEA", "Direct participation"],
                [filled("Guangdong Emission Exchange"), "PRC", "CEA, CCER", "Direct participation"],
                [filled("Core Climate"), "International", "VCC", "Partner relationship"],
            ],
            col_widths=[50 * mm, 28 * mm, 40 * mm, 52 * mm],
        )
        el.append(reg_table)

        # Schedule C
        el.append(PageBreak())
        el.append(Paragraph("SCHEDULE C — DESIGNATED BANK ACCOUNTS AND NOTICES", styles['SectionHeading']))
        el.append(gold_separator())

        el.append(Paragraph("<b>1. CUSTODIAN DESIGNATED BANK ACCOUNT (SEGREGATED CLIENT ACCOUNT)</b>", styles['SubHeading']))
        bank_table = _data_table(styles,
            headers=["Field", "Detail"],
            rows=[
                ["Account Name", filled("Italy Nihao Group Limited — Segregated Account")],
                ["Bank Name", "[Licensed Hong Kong Bank — to be completed upon onboarding]"],
                ["Account Number", "[To be completed upon onboarding]"],
                ["SWIFT Code", "[To be completed upon onboarding]"],
                ["Beneficiary", filled("Italy Nihao Group Limited")],
                ["Reference", "[Client Name — Custodian Account]"],
            ],
            col_widths=[55 * mm, 115 * mm],
        )
        el.append(bank_table)
        el.append(Spacer(1, 5 * mm))

        el.append(Paragraph("<b>2. ADDRESSES FOR NOTICES</b>", styles['SubHeading']))
        cn = client_entity_name or "[Client Full Legal Name]"
        cr = client_representative or "[Designated Contact Person]"
        ce = client_email or "[Email to be provided by Client]"

        notice_table = _data_table(styles,
            headers=["", "Custodian", "Client"],
            rows=[
                ["Entity Name:", filled("Italy Nihao Group Limited"), filled(cn) if client_entity_name else cn],
                ["Attention:", filled("Legal Department"), filled(cr) if client_representative else cr],
                ["Address:", filled("Suite 1201, 12/F, Two Harbourfront, 22 Tak Fung Street, HK"), "[Client Address]"],
                ["Email:", filled("legal@niha.com"), filled(ce) if client_email else ce],
            ],
            col_widths=[30 * mm, 70 * mm, 70 * mm],
        )
        el.append(notice_table)

        # ── KEY TERMS SUMMARY ──
        el.append(Spacer(1, 5 * mm))
        el.append(Paragraph("KEY TERMS SUMMARY", styles['SectionHeading']))
        el.append(thin_separator())

        terms = [
            ("Initial Term", "12 months (auto-renewal)", "Pre-set by NIHA"),
            ("Termination Notice", "90 days written notice", "Pre-set by NIHA"),
            ("Custody Fee", "0.02% / month of AUM", "Pre-set by NIHA"),
            ("Fund Return", "5 Business Days", "Pre-set by NIHA"),
            ("Record Retention", "7 years", "Pre-set by NIHA"),
            ("Confidentiality Survival", "5 years post-termination", "Pre-set by NIHA"),
            ("Non-Circumvention", "2 years post-termination", "Pre-set by NIHA"),
            ("Governing Law", "Hong Kong SAR", "Pre-set by NIHA"),
            ("Dispute Resolution", "Negotiation → Mediation → HKIAC", "Pre-set by NIHA"),
        ]
        el.append(key_terms_table(styles, terms))

        # ── SIGNATURE ──
        el.extend(signature_block(styles, client_entity_name=client_entity_name))

        # ── LEGEND ──
        el.append(Spacer(1, 8 * mm))
        el.append(gold_separator())
        el.append(Paragraph(
            '<i>Note: Text displayed in </i>'
            f'<font name="{NihaFonts.FILLED}" color="{NihaColors.FILLED_BLUE}">this style '
            f'(bold italic, blue)</font>'
            '<i> indicates information pre-completed by NIHA. '
            'Fields with underlines (________) are to be completed by the counterparty.</i>',
            styles['Caption']))

        return el

    return build_niha_pdf(
        doc_ref=ref,
        doc_title="Carbon Credit Custody Agreement",
        content_builder=content,
        confidential=True,
        output_path=output_path,
    )
